version: "3.9.25"


services:
  db:
     image: postgres:15
     container_name: titsly-db
     environment:
       POSTGRES_USER: titsly
       POSTGRES_PASSWORD: titslypass
       POSTGRES_DB: titslydb
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres -d titsly"]
       interval: 10s
       timeout: 5s
       retries: 5

      
         

  web:
    build: .
    container_name: titsly-app
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://titsly:titslypass@db:5432/titslydb
    depends_on:
        db:
          condition: service_healthy
    restart: 'unless-stopped'  
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  postgres_data: